---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valheim-game-name
spec:
  selector:
    matchLabels:
      app: valheim-game-name
      metrics: valheim
  serviceName: "valheim-game-name"
  template:
    metadata:
      labels:
        app: valheim-game-name
        metrics: valheim
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: valheim-game-name
        image: image-registry.openshift-image-registry.svc:5000/games-dev/okd-valheim:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: '2456'
        - name: NAME
          value: "valheim-game-name"
        - name: WORLD
          value: "myworld"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: valheim-secret
              key: serverpassword
        resources:
          limits:
            cpu: "3"
            memory: "6Gi"
          requests:
            cpu: 500m
            memory: "3Gi"
        ports:
        - containerPort: 2456
          protocol: UDP
          name: val1
        - containerPort: 2457
          protocol: UDP
          name: val2
        - containerPort: 2458
          protocol: UDP
          name: val3
        - containerPort: 8080
          protocol: TCP
          name: metrics
        volumeMounts:
        - name: saves
          mountPath: /home/steam/.config/unity3d/IronGate/Valheim
        - name: server
          mountPath: /home/steam/valheim
        - name: backups
          mountPath: /home/steam/backups
  volumeClaimTemplates:
  - metadata:
      name: saves
    spec:
      accessModes: [ "ReadWriteOnce" ]  
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: server
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
  - metadata:
      name: backups
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 25Gi
