apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: steamcmd-20
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.io/steamcmd/steamcmd:ubuntu-20
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: Source
