apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubuntu-22
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.io/ubuntu:22.04
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: Source