kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: game-dev-data
  labels:
    app: game-dev
spec:
 accessModes: [ "ReadWriteOnce" ]
 resources:
   requests:
     storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: game-dev-saves
  labels:
    app: game-dev
spec:
 accessModes: [ "ReadWriteOnce" ]
 resources:
   requests:
     storage: 1Gi